import React, { useState } from 'react';
import { ClipboardPaste, X, Wand2, CheckCircle2, AlertCircle, Film } from 'lucide-react';

export type ImportedVideoConfig = {
  topic?: string;
  audience?: string;
  duration?: string;
  style?: string;
  voiceName?: string;
  veoPrompt?: string;
  veoResolution?: '720p' | '1080p';
  veoAspectRatio?: '16:9' | '9:16';
  mode?: 'narrated' | 'veo';
};

interface PromptImportModalProps {
  isOpen: boolean;
  onClose: () => void;
  onImport: (config: ImportedVideoConfig) => void;
}

function cleanValue(value: unknown): string {
  return typeof value === 'string' ? value.trim() : '';
}

function parsePrompt(raw: string): ImportedVideoConfig {
  const text = raw.trim();
  if (!text) throw new Error('Paste a prompt first.');

  try {
    const parsed = JSON.parse(text);
    const source = parsed?.videoPrompt || parsed?.video || parsed;
    if (source && typeof source === 'object') {
      return {
        topic: cleanValue(source.topic || source.title || source.concept),
        audience: cleanValue(source.audience || source.targetAudience),
        duration: cleanValue(source.duration) || undefined,
        style: cleanValue(source.style || source.visualStyle),
        voiceName: cleanValue(source.voiceName || source.voice),
        veoPrompt: cleanValue(source.veoPrompt || source.cinematicPrompt || source.prompt),
        veoResolution: source.veoResolution === '1080p' ? '1080p' : source.veoResolution === '720p' ? '720p' : undefined,
        veoAspectRatio: source.veoAspectRatio === '9:16' ? '9:16' : source.veoAspectRatio === '16:9' ? '16:9' : undefined,
        mode: source.mode === 'veo' ? 'veo' : source.mode === 'narrated' ? 'narrated' : undefined,
      };
    }
  } catch {
    // Fall through to the human-readable DAVIS_VIDEO_PROMPT parser.
  }

  const result: ImportedVideoConfig = {};
  const lines = text.split(/\r?\n/);
  const aliases: Record<string, keyof ImportedVideoConfig> = {
    topic: 'topic',
    concept: 'topic',
    audience: 'audience',
    'target audience': 'audience',
    duration: 'duration',
    style: 'style',
    'visual style': 'style',
    voice: 'voiceName',
    'voice name': 'voiceName',
    'voiceover': 'voiceName',
    'veo prompt': 'veoPrompt',
    'cinematic prompt': 'veoPrompt',
    resolution: 'veoResolution',
    'veo resolution': 'veoResolution',
    'aspect ratio': 'veoAspectRatio',
    'veo aspect ratio': 'veoAspectRatio',
    mode: 'mode',
  };

  for (const line of lines) {
    const match = line.match(/^\s*(?:[-*]\s*)?([^:]+):\s*(.*?)\s*$/);
    if (!match) continue;
    const key = match[1].trim().toLowerCase();
    const value = match[2].trim();
    const target = aliases[key];
    if (!target || !value) continue;
    (result as any)[target] = value;
  }

  if (!result.topic && !result.veoPrompt) {
    result.topic = text
      .replace(/^DAVIS_VIDEO_PROMPT\s*/i, '')
      .trim();
  }

  if (result.duration) {
    const seconds = Number.parseInt(result.duration, 10);
    result.duration = [60, 90, 120].includes(seconds) ? String(seconds) : '60';
  }
  if (result.voiceName) {
    const allowed = ['Puck', 'Charon', 'Kore', 'Fenrir', 'Zephyr'];
    if (!allowed.includes(result.voiceName)) result.voiceName = undefined;
  }
  if (result.mode === 'veo' && !result.veoPrompt && result.topic) result.veoPrompt = result.topic;
  return result;
}

export function PromptImportModal({ isOpen, onClose, onImport }: PromptImportModalProps) {
  const [value, setValue] = useState('');
  const [error, setError] = useState('');

  if (!isOpen) return null;

  const handleImport = () => {
    try {
      const config = parsePrompt(value);
      if (!config.topic && !config.veoPrompt) {
        throw new Error('I could not find a Topic or Video Prompt in that text.');
      }
      setError('');
      onImport(config);
      setValue('');
    } catch (err: any) {
      setError(err?.message || 'That prompt could not be imported.');
    }
  };

  return (
    <div className="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/55 backdrop-blur-sm p-4">
      <div className="w-full max-w-2xl rounded-2xl bg-white border border-slate-200 shadow-2xl overflow-hidden">
        <div className="flex items-center justify-between px-5 py-4 border-b border-slate-200">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-indigo-100 text-indigo-700 flex items-center justify-center">
              <ClipboardPaste className="w-4.5 h-4.5" />
            </div>
            <div>
              <h2 className="font-bold text-slate-900">Import AI Video Prompt</h2>
              <p className="text-[11px] text-slate-500">Paste a prompt generated by ChatGPT or another AI.</p>
            </div>
          </div>
          <button onClick={onClose} className="p-2 rounded-xl hover:bg-slate-100 text-slate-500 cursor-pointer">
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-5 space-y-4">
          <div className="rounded-xl bg-indigo-50 border border-indigo-100 p-3 text-xs text-indigo-900">
            <div className="font-semibold flex items-center gap-1.5"><Film className="w-3.5 h-3.5" /> Recommended format</div>
            <code className="block mt-2 whitespace-pre-wrap text-[11px] leading-relaxed">DAVIS_VIDEO_PROMPT
Topic: AI prompting for nursery teachers
Audience: Early childhood development teachers
Duration: 90
Style: Educational and engaging
Voice: Puck
Mode: narrated</code>
          </div>

          <textarea
            value={value}
            onChange={(e) => { setValue(e.target.value); setError(''); }}
            placeholder="Paste the complete prompt here..."
            rows={12}
            autoFocus
            className="w-full rounded-xl border border-slate-200 p-3 text-xs leading-relaxed font-mono outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
          />

          {error && (
            <div className="flex items-start gap-2 p-3 rounded-xl bg-rose-50 border border-rose-200 text-rose-800 text-xs">
              <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
              <span>{error}</span>
            </div>
          )}

          <div className="flex items-center justify-between gap-3">
            <div className="text-[11px] text-slate-500">
              <CheckCircle2 className="w-3.5 h-3.5 inline mr-1 text-emerald-600" />
              No extra API key is required for importing.
            </div>
            <button
              onClick={handleImport}
              disabled={!value.trim()}
              className="rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white px-5 py-2.5 text-xs font-bold flex items-center gap-2 disabled:opacity-40 cursor-pointer"
            >
              <Wand2 className="w-4 h-4" />
              Import to Video Studio
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
